language: android
android:
  components:
  - build-tools-19.0.2
branches:
  only:
  - master
  - travis-test
env:
  global:
  - secure: Rh0EaEBPqBrEUWPnvM3qdVfQek1Y89zaG9wEPYTPvsGPVV5P7mc4V1nlc3GD2T++YPcSWo/QZwn80THQdkDvht0kxdaaJYcJiH6ZkhQylG1voq88BDGqwyAM/2yvIdG12wuBMyiVqKMZW0d3zy7VHbsrz9xdTlgK82p/BYtuuNU=
  - secure: Vat9uUbmBvbdnIWhhr4NVGxx25VpzsBo5VAf44oTzY6Eh3Ya3ECM+8pAr/6BJph7O7TDAcVDC/D5LL2K7OHOBRx+ike8W1GOa005dtj5gYxW96gZ3wLOB+CqCnPfHdyU8Jp+Rd0IAFMlNo/6q+QyIXu98g+H8rArsSqhjRwt+bE=

before_install:
- export ANDROID_TARGET=android-19
- export ANDROID_ABI=armeabi-v7a
- echo no | android create avd --force --name test-avd --target $ANDROID_TARGET --abi $ANDROID_ABI
- emulator -avd test-avd -no-skin -no-audio -no-window &

before_script:
- ./wait_for_emulator.sh

script:
- "./gradlew assemble connectedCheck"
